### ISSUE TITLE
Using TailwindCSS without CDN

### ISSUE THREAD

**Issue by Suman2023** [PyHAT-stack/web-async-patterns#1]
Hello,
I have been learning Django from some time and got here through the DjangoCon video. Here i see using the tailwindcss from CDN which is not recommended in the docs. How do we solve that i have been looking for this but most of them added too many complexities. 
Can you provide a better and optimized way as this is all about lowering the loading time and size.
Thanks.

**Comment by Chris-May** [comment]
Hello, Suman!

You are correct, using Tailwind CSS through the CDN is not recommended for production.

When I set up my projects, I use the [Tailwind CLI tool as written in their documentation](https://tailwindcss.com/docs/installation).

However, several people I know enjoy using the `pytailwindcss` [PYPI package](https://github.com/timonweb/pytailwindcss).
